### ISSUE TITLE
rstml-based html-to-string-macro crate?

### ISSUE THREAD

**Issue by 0atman** [rs-tml/rstml#23]
Hello! 

Could you publish https://github.com/rs-tml/rstml/tree/main/examples/html-to-string-macro as a crate? I'm hoping to switch to your fork and I just need simple string rendering.

Thank you so much for picking up this project! :-)

**Comment by vldm** [comment]
Hi, html-to-string-macro was planned as an example of ide support in rstml, since most of improvements in rstml was related to IDE support.
The one significant exception that i can remember is "unquoted text", which is powerful only in nightly.

I already have pushed some stuff related to IDE support into this example (_You can check test.rs in your ide and see, demo of semantic highlight/goto def/docs._), i also broke "empty elements" during refactoring.

This changes made example less useful as independent crate.


In https://github.com/rs-tml/rstml/pull/24 i have tried to revert those thing back and split ide and regular version of macro.
I also pushed fixed version with name [rstml-to-string-macro](https://crates.io/crates/rstml-to-string-macro). I believe that **stable** code should not change so rapid, so don't expect much from this release.

**Comment by 0atman** [comment]
FANTASTIC, thank you so much!
